// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvUqFF0SlLIK_ncHS3XTxl1Bt98vL1Mzg',
    appId: '1:230814657090:web:c8cc643fe4b94cd850dbdb',
    messagingSenderId: '230814657090',
    projectId: 'letterbloom-727346',
    authDomain: 'letterbloom-727346.firebaseapp.com',
    storageBucket: 'letterbloom-727346.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF1KncVkPrej6KeDeZDAbDlleOcwRmjQc',
    appId: '1:230814657090:android:1a3dcb51e658022950dbdb',
    messagingSenderId: '230814657090',
    projectId: 'letterbloom-727346',
    storageBucket: 'letterbloom-727346.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDQDGkkeOagskjWQKn25a9RKQ7iE26rQs',
    appId: '1:230814657090:ios:cf146c233c05576f50dbdb',
    messagingSenderId: '230814657090',
    projectId: 'letterbloom-727346',
    storageBucket: 'letterbloom-727346.firebasestorage.app',
    iosBundleId: 'com.letterbloom.letterBloom',
  );

}